import fs from 'node:fs/promises'
import path from 'node:path'
import PDFDocument from 'pdfkit'
import type { ImpactReport } from './types.js'

export async function writeImpactReportPdf(report: ImpactReport, outputDir = path.resolve('data/reports')): Promise<string> {
  await fs.mkdir(outputDir, { recursive: true })
  const filePath = path.join(outputDir, `${report.id}.pdf`)

  await new Promise<void>((resolve, reject) => {
    const doc = new PDFDocument({ margin: 48, size: 'A4' })
    const chunks: Buffer[] = []
    doc.on('data', (chunk: Buffer) => chunks.push(Buffer.from(chunk)))
    doc.on('end', () => {
      fs.writeFile(filePath, Buffer.concat(chunks)).then(() => resolve()).catch(reject)
    })
    doc.on('error', reject)

    doc.fontSize(20).text(report.title, { underline: true })
    doc.moveDown()
    doc.fontSize(10).fillColor('#555').text(`${report.period_start} - ${report.period_end}`)
    doc.moveDown()
    doc.fillColor('#111').fontSize(13).text('Summary')
    doc.moveDown(0.5)
    doc.fontSize(11).text(report.summary, { lineGap: 4 })
    doc.moveDown()
    doc.fontSize(13).text('Metrics Basis')
    doc.moveDown(0.5)
    doc.fontSize(9).text(JSON.stringify(report.metrics_json, null, 2), { lineGap: 2 })
    doc.moveDown()
    doc.fontSize(13).text('Recommendations')
    doc.moveDown(0.5)
    for (const recommendation of report.recommendations) {
      doc.fontSize(11).text(`- ${recommendation}`, { lineGap: 3 })
    }
    doc.moveDown()
    doc.fontSize(9).fillColor('#777').text('Generated by TrendDo Admin. External tourism indicators, when present, are auxiliary trend indicators only.')
    doc.end()
  })

  return filePath
}
